package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant2 {
  private static final String TAG = "GeneratedPluginRegistrant2";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.bingo.flutter_module_host.FlutterModuleHostPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_module_host, com.bingo.flutter_module_host.FlutterModuleHostPlugin", e);
    }
  }
}
